// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/mixers (interfaces: FFmpegManager)
//
// Generated by this command:
//
//	mockgen -destination=mocks/ffmpeg_manager.go -package=mocks github.com/imtaco/audio-rtc-exp/mixers FFmpegManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockFFmpegManager is a mock of FFmpegManager interface.
type MockFFmpegManager struct {
	ctrl     *gomock.Controller
	recorder *MockFFmpegManagerMockRecorder
	isgomock struct{}
}

// MockFFmpegManagerMockRecorder is the mock recorder for MockFFmpegManager.
type MockFFmpegManagerMockRecorder struct {
	mock *MockFFmpegManager
}

// NewMockFFmpegManager creates a new mock instance.
func NewMockFFmpegManager(ctrl *gomock.Controller) *MockFFmpegManager {
	mock := &MockFFmpegManager{ctrl: ctrl}
	mock.recorder = &MockFFmpegManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFFmpegManager) EXPECT() *MockFFmpegManagerMockRecorder {
	return m.recorder
}

// StartFFmpeg mocks base method.
func (m *MockFFmpegManager) StartFFmpeg(roomID string, rtpPort int, createdAt time.Time, nonce string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartFFmpeg", roomID, rtpPort, createdAt, nonce)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartFFmpeg indicates an expected call of StartFFmpeg.
func (mr *MockFFmpegManagerMockRecorder) StartFFmpeg(roomID, rtpPort, createdAt, nonce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartFFmpeg", reflect.TypeOf((*MockFFmpegManager)(nil).StartFFmpeg), roomID, rtpPort, createdAt, nonce)
}

// Stop mocks base method.
func (m *MockFFmpegManager) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockFFmpegManagerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockFFmpegManager)(nil).Stop))
}

// StopFFmpeg mocks base method.
func (m *MockFFmpegManager) StopFFmpeg(roomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopFFmpeg", roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopFFmpeg indicates an expected call of StopFFmpeg.
func (mr *MockFFmpegManagerMockRecorder) StopFFmpeg(roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopFFmpeg", reflect.TypeOf((*MockFFmpegManager)(nil).StopFFmpeg), roomID)
}
