// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/mixers (interfaces: PortManager)
//
// Generated by this command:
//
//	mockgen -destination=mocks/port_manager.go -package=mocks github.com/imtaco/audio-rtc-exp/mixers PortManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPortManager is a mock of PortManager interface.
type MockPortManager struct {
	ctrl     *gomock.Controller
	recorder *MockPortManagerMockRecorder
	isgomock struct{}
}

// MockPortManagerMockRecorder is the mock recorder for MockPortManager.
type MockPortManagerMockRecorder struct {
	mock *MockPortManager
}

// NewMockPortManager creates a new mock instance.
func NewMockPortManager(ctrl *gomock.Controller) *MockPortManager {
	mock := &MockPortManager{ctrl: ctrl}
	mock.recorder = &MockPortManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortManager) EXPECT() *MockPortManagerMockRecorder {
	return m.recorder
}

// GetFreeRTPPort mocks base method.
func (m *MockPortManager) GetFreeRTPPort() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFreeRTPPort")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFreeRTPPort indicates an expected call of GetFreeRTPPort.
func (mr *MockPortManagerMockRecorder) GetFreeRTPPort() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFreeRTPPort", reflect.TypeOf((*MockPortManager)(nil).GetFreeRTPPort))
}
