// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/internal/jwt (interfaces: JWTAuth)
//
// Generated by this command:
//
//	mockgen -destination=mocks/jwt.go -package=mocks github.com/imtaco/audio-rtc-exp/internal/jwt JWTAuth
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	jwt "github.com/imtaco/audio-rtc-exp/internal/jwt"
	gomock "go.uber.org/mock/gomock"
)

// MockJWTAuth is a mock of JWTAuth interface.
type MockJWTAuth struct {
	ctrl     *gomock.Controller
	recorder *MockJWTAuthMockRecorder
	isgomock struct{}
}

// MockJWTAuthMockRecorder is the mock recorder for MockJWTAuth.
type MockJWTAuthMockRecorder struct {
	mock *MockJWTAuth
}

// NewMockJWTAuth creates a new mock instance.
func NewMockJWTAuth(ctrl *gomock.Controller) *MockJWTAuth {
	mock := &MockJWTAuth{ctrl: ctrl}
	mock.recorder = &MockJWTAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTAuth) EXPECT() *MockJWTAuthMockRecorder {
	return m.recorder
}

// Sign mocks base method.
func (m *MockJWTAuth) Sign(userID, roomID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sign", userID, roomID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sign indicates an expected call of Sign.
func (mr *MockJWTAuthMockRecorder) Sign(userID, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*MockJWTAuth)(nil).Sign), userID, roomID)
}

// Verify mocks base method.
func (m *MockJWTAuth) Verify(tokenString string) (*jwt.JWTPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", tokenString)
	ret0, _ := ret[0].(*jwt.JWTPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockJWTAuthMockRecorder) Verify(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockJWTAuth)(nil).Verify), tokenString)
}
