// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/internal/reswatcher/etcd (interfaces: HealthyModuleWatcher)
//
// Generated by this command:
//
//	mockgen -destination=mocks/module_watcher.go -package=mocks github.com/imtaco/audio-rtc-exp/internal/reswatcher/etcd HealthyModuleWatcher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	etcdstate "github.com/imtaco/audio-rtc-exp/internal/etcdstate"
	gomock "go.uber.org/mock/gomock"
)

// MockHealthyModuleWatcher is a mock of HealthyModuleWatcher interface.
type MockHealthyModuleWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockHealthyModuleWatcherMockRecorder
	isgomock struct{}
}

// MockHealthyModuleWatcherMockRecorder is the mock recorder for MockHealthyModuleWatcher.
type MockHealthyModuleWatcherMockRecorder struct {
	mock *MockHealthyModuleWatcher
}

// NewMockHealthyModuleWatcher creates a new mock instance.
func NewMockHealthyModuleWatcher(ctrl *gomock.Controller) *MockHealthyModuleWatcher {
	mock := &MockHealthyModuleWatcher{ctrl: ctrl}
	mock.recorder = &MockHealthyModuleWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthyModuleWatcher) EXPECT() *MockHealthyModuleWatcherMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockHealthyModuleWatcher) Get(id string) (etcdstate.ModuleState, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(etcdstate.ModuleState)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHealthyModuleWatcherMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHealthyModuleWatcher)(nil).Get), id)
}

// GetAllHealthy mocks base method.
func (m *MockHealthyModuleWatcher) GetAllHealthy() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllHealthy")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAllHealthy indicates an expected call of GetAllHealthy.
func (mr *MockHealthyModuleWatcherMockRecorder) GetAllHealthy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllHealthy", reflect.TypeOf((*MockHealthyModuleWatcher)(nil).GetAllHealthy))
}

// GetCachedState mocks base method.
func (m *MockHealthyModuleWatcher) GetCachedState(id string) (*etcdstate.ModuleState, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedState", id)
	ret0, _ := ret[0].(*etcdstate.ModuleState)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetCachedState indicates an expected call of GetCachedState.
func (mr *MockHealthyModuleWatcherMockRecorder) GetCachedState(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedState", reflect.TypeOf((*MockHealthyModuleWatcher)(nil).GetCachedState), id)
}

// Has mocks base method.
func (m *MockHealthyModuleWatcher) Has(id string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Has indicates an expected call of Has.
func (mr *MockHealthyModuleWatcherMockRecorder) Has(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*MockHealthyModuleWatcher)(nil).Has), id)
}

// Restart mocks base method.
func (m *MockHealthyModuleWatcher) Restart() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Restart")
}

// Restart indicates an expected call of Restart.
func (mr *MockHealthyModuleWatcherMockRecorder) Restart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockHealthyModuleWatcher)(nil).Restart))
}

// Start mocks base method.
func (m *MockHealthyModuleWatcher) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockHealthyModuleWatcherMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockHealthyModuleWatcher)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockHealthyModuleWatcher) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockHealthyModuleWatcherMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockHealthyModuleWatcher)(nil).Stop))
}
