// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/rooms/service (interfaces: RoomWatcherWithStats)
//
// Generated by this command:
//
//	mockgen -destination=mocks/room_watcher.go -package=mocks github.com/imtaco/audio-rtc-exp/rooms/service RoomWatcherWithStats
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	etcdstate "github.com/imtaco/audio-rtc-exp/internal/etcdstate"
)

// MockRoomWatcherWithStats is a mock of RoomWatcherWithStats interface.
type MockRoomWatcherWithStats struct {
	ctrl     *gomock.Controller
	recorder *MockRoomWatcherWithStatsMockRecorder
	isgomock struct{}
}

// MockRoomWatcherWithStatsMockRecorder is the mock recorder for MockRoomWatcherWithStats.
type MockRoomWatcherWithStatsMockRecorder struct {
	mock *MockRoomWatcherWithStats
}

// NewMockRoomWatcherWithStats creates a new mock instance.
func NewMockRoomWatcherWithStats(ctrl *gomock.Controller) *MockRoomWatcherWithStats {
	mock := &MockRoomWatcherWithStats{ctrl: ctrl}
	mock.recorder = &MockRoomWatcherWithStatsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomWatcherWithStats) EXPECT() *MockRoomWatcherWithStatsMockRecorder {
	return m.recorder
}

// GetCachedState mocks base method.
func (m *MockRoomWatcherWithStats) GetCachedState(id string) (*etcdstate.RoomState, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedState", id)
	ret0, _ := ret[0].(*etcdstate.RoomState)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetCachedState indicates an expected call of GetCachedState.
func (mr *MockRoomWatcherWithStatsMockRecorder) GetCachedState(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedState", reflect.TypeOf((*MockRoomWatcherWithStats)(nil).GetCachedState), id)
}

// GetJanusStreamCount mocks base method.
func (m *MockRoomWatcherWithStats) GetJanusStreamCount(janusID string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJanusStreamCount", janusID)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetJanusStreamCount indicates an expected call of GetJanusStreamCount.
func (mr *MockRoomWatcherWithStatsMockRecorder) GetJanusStreamCount(janusID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJanusStreamCount", reflect.TypeOf((*MockRoomWatcherWithStats)(nil).GetJanusStreamCount), janusID)
}

// GetMixerStreamCount mocks base method.
func (m *MockRoomWatcherWithStats) GetMixerStreamCount(mixerID string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMixerStreamCount", mixerID)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetMixerStreamCount indicates an expected call of GetMixerStreamCount.
func (mr *MockRoomWatcherWithStatsMockRecorder) GetMixerStreamCount(mixerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMixerStreamCount", reflect.TypeOf((*MockRoomWatcherWithStats)(nil).GetMixerStreamCount), mixerID)
}

// Restart mocks base method.
func (m *MockRoomWatcherWithStats) Restart() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Restart")
}

// Restart indicates an expected call of Restart.
func (mr *MockRoomWatcherWithStatsMockRecorder) Restart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockRoomWatcherWithStats)(nil).Restart))
}

// Start mocks base method.
func (m *MockRoomWatcherWithStats) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockRoomWatcherWithStatsMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRoomWatcherWithStats)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockRoomWatcherWithStats) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockRoomWatcherWithStatsMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockRoomWatcherWithStats)(nil).Stop))
}
