// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/users (interfaces: RoomsState)
//
// Generated by this command:
//
//	mockgen -destination=users/mocks/rooms_state.go -package=mocks github.com/imtaco/audio-rtc-exp/users RoomsState
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	users "github.com/imtaco/audio-rtc-exp/users"
)

// MockRoomsState is a mock of RoomsState interface.
type MockRoomsState struct {
	ctrl     *gomock.Controller
	recorder *MockRoomsStateMockRecorder
	isgomock struct{}
}

// MockRoomsStateMockRecorder is the mock recorder for MockRoomsState.
type MockRoomsStateMockRecorder struct {
	mock *MockRoomsState
}

// NewMockRoomsState creates a new mock instance.
func NewMockRoomsState(ctrl *gomock.Controller) *MockRoomsState {
	mock := &MockRoomsState{ctrl: ctrl}
	mock.recorder = &MockRoomsStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomsState) EXPECT() *MockRoomsStateMockRecorder {
	return m.recorder
}

// CheckTimeout mocks base method.
func (m *MockRoomsState) CheckTimeout(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTimeout", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckTimeout indicates an expected call of CheckTimeout.
func (mr *MockRoomsStateMockRecorder) CheckTimeout(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTimeout", reflect.TypeOf((*MockRoomsState)(nil).CheckTimeout), ctx)
}

// CreateUser mocks base method.
func (m *MockRoomsState) CreateUser(ctx context.Context, roomID, userID string, u *users.User) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, roomID, userID, u)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRoomsStateMockRecorder) CreateUser(ctx, roomID, userID, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRoomsState)(nil).CreateUser), ctx, roomID, userID, u)
}

// GetRoomUsers mocks base method.
func (m *MockRoomsState) GetRoomUsers(ctx context.Context, roomID string) map[string]users.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomUsers", ctx, roomID)
	ret0, _ := ret[0].(map[string]users.User)
	return ret0
}

// GetRoomUsers indicates an expected call of GetRoomUsers.
func (mr *MockRoomsStateMockRecorder) GetRoomUsers(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomUsers", reflect.TypeOf((*MockRoomsState)(nil).GetRoomUsers), ctx, roomID)
}

// Rebuild mocks base method.
func (m *MockRoomsState) Rebuild(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rebuild", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rebuild indicates an expected call of Rebuild.
func (mr *MockRoomsStateMockRecorder) Rebuild(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rebuild", reflect.TypeOf((*MockRoomsState)(nil).Rebuild), ctx)
}

// RemoveUser mocks base method.
func (m *MockRoomsState) RemoveUser(ctx context.Context, roomID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUser", ctx, roomID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveUser indicates an expected call of RemoveUser.
func (mr *MockRoomsStateMockRecorder) RemoveUser(ctx, roomID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUser", reflect.TypeOf((*MockRoomsState)(nil).RemoveUser), ctx, roomID, userID)
}

// UpdateUserStatus mocks base method.
func (m *MockRoomsState) UpdateUserStatus(ctx context.Context, roomID, userID string, u *users.User) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserStatus", ctx, roomID, userID, u)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserStatus indicates an expected call of UpdateUserStatus.
func (mr *MockRoomsStateMockRecorder) UpdateUserStatus(ctx, roomID, userID, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserStatus", reflect.TypeOf((*MockRoomsState)(nil).UpdateUserStatus), ctx, roomID, userID, u)
}
