// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/users (interfaces: UserService)
//
// Generated by this command:
//
//	mockgen -destination=users/mocks/user_service.go -package=mocks github.com/imtaco/audio-rtc-exp/users UserService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	constants "github.com/imtaco/audio-rtc-exp/internal/constants"
	"github.com/imtaco/audio-rtc-exp/users"
	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserService) CreateUser(ctx context.Context, roomId, userId, role string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, roomId, userId, role)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserServiceMockRecorder) CreateUser(ctx, roomId, userId, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserService)(nil).CreateUser), ctx, roomId, userId, role)
}

// DeleteUser mocks base method.
func (m *MockUserService) DeleteUser(ctx context.Context, roomId, userId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, roomId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserServiceMockRecorder) DeleteUser(ctx, roomId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserService)(nil).DeleteUser), ctx, roomId, userId)
}

// GetActiveRoomUsers mocks base method.
func (m *MockUserService) GetActiveRoomUsers(ctx context.Context, roomId string) ([]*users.RoomUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveRoomUsers", ctx, roomId)
	ret0, _ := ret[0].([]*users.RoomUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveRoomUsers indicates an expected call of GetActiveRoomUsers.
func (mr *MockUserServiceMockRecorder) GetActiveRoomUsers(ctx, roomId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveRoomUsers", reflect.TypeOf((*MockUserService)(nil).GetActiveRoomUsers), ctx, roomId)
}

// SetUserStatus mocks base method.
func (m *MockUserService) SetUserStatus(ctx context.Context, roomId, userId string, status constants.AnchorStatus, gen int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserStatus", ctx, roomId, userId, status, gen)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserStatus indicates an expected call of SetUserStatus.
func (mr *MockUserServiceMockRecorder) SetUserStatus(ctx, roomId, userId, status, gen any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserStatus", reflect.TypeOf((*MockUserService)(nil).SetUserStatus), ctx, roomId, userId, status, gen)
}

// Start mocks base method.
func (m *MockUserService) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockUserServiceMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockUserService)(nil).Start), ctx)
}
