// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/wsgateway (interfaces: JanusProxy)
//
// Generated by this command:
//
//	mockgen -destination=mocks/janus_proxy.go -package=mocks github.com/imtaco/audio-rtc-exp/wsgateway JanusProxy
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	etcdstate "github.com/imtaco/audio-rtc-exp/internal/etcdstate"
	janus "github.com/imtaco/audio-rtc-exp/internal/janus"
	gomock "go.uber.org/mock/gomock"
)

// MockJanusProxy is a mock of JanusProxy interface.
type MockJanusProxy struct {
	ctrl     *gomock.Controller
	recorder *MockJanusProxyMockRecorder
	isgomock struct{}
}

// MockJanusProxyMockRecorder is the mock recorder for MockJanusProxy.
type MockJanusProxyMockRecorder struct {
	mock *MockJanusProxy
}

// NewMockJanusProxy creates a new mock instance.
func NewMockJanusProxy(ctrl *gomock.Controller) *MockJanusProxy {
	mock := &MockJanusProxy{ctrl: ctrl}
	mock.recorder = &MockJanusProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJanusProxy) EXPECT() *MockJanusProxyMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockJanusProxy) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockJanusProxyMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockJanusProxy)(nil).Close))
}

// GetJanusAPI mocks base method.
func (m *MockJanusProxy) GetJanusAPI(roomID string) janus.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJanusAPI", roomID)
	ret0, _ := ret[0].(janus.API)
	return ret0
}

// GetJanusAPI indicates an expected call of GetJanusAPI.
func (mr *MockJanusProxyMockRecorder) GetJanusAPI(roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJanusAPI", reflect.TypeOf((*MockJanusProxy)(nil).GetJanusAPI), roomID)
}

// GetJanusRoomID mocks base method.
func (m *MockJanusProxy) GetJanusRoomID(roomID string) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJanusRoomID", roomID)
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetJanusRoomID indicates an expected call of GetJanusRoomID.
func (mr *MockJanusProxyMockRecorder) GetJanusRoomID(roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJanusRoomID", reflect.TypeOf((*MockJanusProxy)(nil).GetJanusRoomID), roomID)
}

// GetRoomLiveMeta mocks base method.
func (m *MockJanusProxy) GetRoomLiveMeta(roomId string) *etcdstate.LiveMeta {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomLiveMeta", roomId)
	ret0, _ := ret[0].(*etcdstate.LiveMeta)
	return ret0
}

// GetRoomLiveMeta indicates an expected call of GetRoomLiveMeta.
func (mr *MockJanusProxyMockRecorder) GetRoomLiveMeta(roomId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomLiveMeta", reflect.TypeOf((*MockJanusProxy)(nil).GetRoomLiveMeta), roomId)
}

// GetRoomMeta mocks base method.
func (m *MockJanusProxy) GetRoomMeta(roomId string) *etcdstate.Meta {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomMeta", roomId)
	ret0, _ := ret[0].(*etcdstate.Meta)
	return ret0
}

// GetRoomMeta indicates an expected call of GetRoomMeta.
func (mr *MockJanusProxyMockRecorder) GetRoomMeta(roomId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomMeta", reflect.TypeOf((*MockJanusProxy)(nil).GetRoomMeta), roomId)
}

// Open mocks base method.
func (m *MockJanusProxy) Open(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockJanusProxyMockRecorder) Open(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockJanusProxy)(nil).Open), ctx)
}
