// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/wsgateway (interfaces: JanusTokenCodec)
//
// Generated by this command:
//
//	mockgen -destination=mocks/token_codec.go -package=mocks github.com/imtaco/audio-rtc-exp/wsgateway JanusTokenCodec
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockJanusTokenCodec is a mock of JanusTokenCodec interface.
type MockJanusTokenCodec struct {
	ctrl     *gomock.Controller
	recorder *MockJanusTokenCodecMockRecorder
	isgomock struct{}
}

// MockJanusTokenCodecMockRecorder is the mock recorder for MockJanusTokenCodec.
type MockJanusTokenCodecMockRecorder struct {
	mock *MockJanusTokenCodec
}

// NewMockJanusTokenCodec creates a new mock instance.
func NewMockJanusTokenCodec(ctrl *gomock.Controller) *MockJanusTokenCodec {
	mock := &MockJanusTokenCodec{ctrl: ctrl}
	mock.recorder = &MockJanusTokenCodecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJanusTokenCodec) EXPECT() *MockJanusTokenCodecMockRecorder {
	return m.recorder
}

// Decode mocks base method.
func (m *MockJanusTokenCodec) Decode(roomKey, token string) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", roomKey, token)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Decode indicates an expected call of Decode.
func (mr *MockJanusTokenCodecMockRecorder) Decode(roomKey, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockJanusTokenCodec)(nil).Decode), roomKey, token)
}

// Encode mocks base method.
func (m *MockJanusTokenCodec) Encode(roomKey string, sessionID, handleID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", roomKey, sessionID, handleID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encode indicates an expected call of Encode.
func (mr *MockJanusTokenCodecMockRecorder) Encode(roomKey, sessionID, handleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockJanusTokenCodec)(nil).Encode), roomKey, sessionID, handleID)
}
