// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/internal/watcher (interfaces: StateTransformer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/state_transformer.go -package=mocks github.com/imtaco/audio-rtc-exp/internal/watcher StateTransformer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStateTransformer is a mock of StateTransformer interface.
type MockStateTransformer[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockStateTransformerMockRecorder[T]
	isgomock struct{}
}

// MockStateTransformerMockRecorder is the mock recorder for MockStateTransformer.
type MockStateTransformerMockRecorder[T any] struct {
	mock *MockStateTransformer[T]
}

// NewMockStateTransformer creates a new mock instance.
func NewMockStateTransformer[T any](ctrl *gomock.Controller) *MockStateTransformer[T] {
	mock := &MockStateTransformer[T]{ctrl: ctrl}
	mock.recorder = &MockStateTransformerMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateTransformer[T]) EXPECT() *MockStateTransformerMockRecorder[T] {
	return m.recorder
}

// NewState mocks base method.
func (m *MockStateTransformer[T]) NewState(id, keyType string, data []byte, currentState *T) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewState", id, keyType, data, currentState)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewState indicates an expected call of NewState.
func (mr *MockStateTransformerMockRecorder[T]) NewState(id, keyType, data, currentState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewState", reflect.TypeOf((*MockStateTransformer[T])(nil).NewState), id, keyType, data, currentState)
}

// RebuildEnd mocks base method.
func (m *MockStateTransformer[T]) RebuildEnd(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebuildEnd", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebuildEnd indicates an expected call of RebuildEnd.
func (mr *MockStateTransformerMockRecorder[T]) RebuildEnd(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebuildEnd", reflect.TypeOf((*MockStateTransformer[T])(nil).RebuildEnd), ctx)
}

// RebuildStart mocks base method.
func (m *MockStateTransformer[T]) RebuildStart(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebuildStart", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebuildStart indicates an expected call of RebuildStart.
func (mr *MockStateTransformerMockRecorder[T]) RebuildStart(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebuildStart", reflect.TypeOf((*MockStateTransformer[T])(nil).RebuildStart), ctx)
}

// RebuildState mocks base method.
func (m *MockStateTransformer[T]) RebuildState(ctx context.Context, id string, etcdData *T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebuildState", ctx, id, etcdData)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebuildState indicates an expected call of RebuildState.
func (mr *MockStateTransformerMockRecorder[T]) RebuildState(ctx, id, etcdData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebuildState", reflect.TypeOf((*MockStateTransformer[T])(nil).RebuildState), ctx, id, etcdData)
}
