// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/internal/watcher (interfaces: Watcher)
//
// Generated by this command:
//
//	mockgen -destination=mocks/watcher.go -package=mocks github.com/imtaco/audio-rtc-exp/internal/watcher Watcher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWatcher is a mock of Watcher interface.
type MockWatcher[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockWatcherMockRecorder[T]
	isgomock struct{}
}

// MockWatcherMockRecorder is the mock recorder for MockWatcher.
type MockWatcherMockRecorder[T any] struct {
	mock *MockWatcher[T]
}

// NewMockWatcher creates a new mock instance.
func NewMockWatcher[T any](ctrl *gomock.Controller) *MockWatcher[T] {
	mock := &MockWatcher[T]{ctrl: ctrl}
	mock.recorder = &MockWatcherMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatcher[T]) EXPECT() *MockWatcherMockRecorder[T] {
	return m.recorder
}

// GetCachedState mocks base method.
func (m *MockWatcher[T]) GetCachedState(id string) (*T, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedState", id)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetCachedState indicates an expected call of GetCachedState.
func (mr *MockWatcherMockRecorder[T]) GetCachedState(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedState", reflect.TypeOf((*MockWatcher[T])(nil).GetCachedState), id)
}

// Restart mocks base method.
func (m *MockWatcher[T]) Restart() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Restart")
}

// Restart indicates an expected call of Restart.
func (mr *MockWatcherMockRecorder[T]) Restart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockWatcher[T])(nil).Restart))
}

// Start mocks base method.
func (m *MockWatcher[T]) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockWatcherMockRecorder[T]) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockWatcher[T])(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockWatcher[T]) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockWatcherMockRecorder[T]) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockWatcher[T])(nil).Stop))
}
