// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/hlsserver (interfaces: RoomWatcher)
//
// Generated by this command:
//
//	mockgen -destination=mocks/watcher.go -package=mocks github.com/imtaco/audio-rtc-exp/hlsserver RoomWatcher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	etcdstate "github.com/imtaco/audio-rtc-exp/internal/etcdstate"
)

// MockRoomWatcher is a mock of RoomWatcher interface.
type MockRoomWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockRoomWatcherMockRecorder
	isgomock struct{}
}

// MockRoomWatcherMockRecorder is the mock recorder for MockRoomWatcher.
type MockRoomWatcherMockRecorder struct {
	mock *MockRoomWatcher
}

// NewMockRoomWatcher creates a new mock instance.
func NewMockRoomWatcher(ctrl *gomock.Controller) *MockRoomWatcher {
	mock := &MockRoomWatcher{ctrl: ctrl}
	mock.recorder = &MockRoomWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomWatcher) EXPECT() *MockRoomWatcherMockRecorder {
	return m.recorder
}

// GetActiveLiveMeta mocks base method.
func (m *MockRoomWatcher) GetActiveLiveMeta(roomID string) *etcdstate.LiveMeta {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveLiveMeta", roomID)
	ret0, _ := ret[0].(*etcdstate.LiveMeta)
	return ret0
}

// GetActiveLiveMeta indicates an expected call of GetActiveLiveMeta.
func (mr *MockRoomWatcherMockRecorder) GetActiveLiveMeta(roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveLiveMeta", reflect.TypeOf((*MockRoomWatcher)(nil).GetActiveLiveMeta), roomID)
}

// GetCachedState mocks base method.
func (m *MockRoomWatcher) GetCachedState(id string) (*etcdstate.RoomState, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedState", id)
	ret0, _ := ret[0].(*etcdstate.RoomState)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetCachedState indicates an expected call of GetCachedState.
func (mr *MockRoomWatcherMockRecorder) GetCachedState(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedState", reflect.TypeOf((*MockRoomWatcher)(nil).GetCachedState), id)
}

// Restart mocks base method.
func (m *MockRoomWatcher) Restart() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Restart")
}

// Restart indicates an expected call of Restart.
func (mr *MockRoomWatcherMockRecorder) Restart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockRoomWatcher)(nil).Restart))
}

// Start mocks base method.
func (m *MockRoomWatcher) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockRoomWatcherMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRoomWatcher)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockRoomWatcher) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockRoomWatcherMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockRoomWatcher)(nil).Stop))
}
