// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/internal/janus (interfaces: Admin)
//
// Generated by this command:
//
//	mockgen -destination=mocks/admin.go -package=mocks github.com/imtaco/audio-rtc-exp/internal/janus Admin
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	janus "github.com/imtaco/audio-rtc-exp/internal/janus"
)

// MockAdmin is a mock of Admin interface.
type MockAdmin struct {
	ctrl     *gomock.Controller
	recorder *MockAdminMockRecorder
	isgomock struct{}
}

// MockAdminMockRecorder is the mock recorder for MockAdmin.
type MockAdminMockRecorder struct {
	mock *MockAdmin
}

// NewMockAdmin creates a new mock instance.
func NewMockAdmin(ctrl *gomock.Controller) *MockAdmin {
	mock := &MockAdmin{ctrl: ctrl}
	mock.recorder = &MockAdminMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdmin) EXPECT() *MockAdminMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockAdmin) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockAdminMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAdmin)(nil).Close))
}

// CreateRTPForwarder mocks base method.
func (m *MockAdmin) CreateRTPForwarder(ctx context.Context, roomID int64, host string, port int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRTPForwarder", ctx, roomID, host, port)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRTPForwarder indicates an expected call of CreateRTPForwarder.
func (mr *MockAdminMockRecorder) CreateRTPForwarder(ctx, roomID, host, port any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRTPForwarder", reflect.TypeOf((*MockAdmin)(nil).CreateRTPForwarder), ctx, roomID, host, port)
}

// CreateRoom mocks base method.
func (m *MockAdmin) CreateRoom(ctx context.Context, roomID int64, description, pin string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, roomID, description, pin)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockAdminMockRecorder) CreateRoom(ctx, roomID, description, pin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockAdmin)(nil).CreateRoom), ctx, roomID, description, pin)
}

// Destroy mocks base method.
func (m *MockAdmin) Destroy(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Destroy", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Destroy indicates an expected call of Destroy.
func (mr *MockAdminMockRecorder) Destroy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroy", reflect.TypeOf((*MockAdmin)(nil).Destroy), ctx)
}

// DestroyRoom mocks base method.
func (m *MockAdmin) DestroyRoom(ctx context.Context, roomID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyRoom", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyRoom indicates an expected call of DestroyRoom.
func (mr *MockAdminMockRecorder) DestroyRoom(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyRoom", reflect.TypeOf((*MockAdmin)(nil).DestroyRoom), ctx, roomID)
}

// GetEvents mocks base method.
func (m *MockAdmin) GetEvents(ctx context.Context, maxEvents int) ([]*janus.JanusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvents", ctx, maxEvents)
	ret0, _ := ret[0].([]*janus.JanusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvents indicates an expected call of GetEvents.
func (mr *MockAdminMockRecorder) GetEvents(ctx, maxEvents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvents", reflect.TypeOf((*MockAdmin)(nil).GetEvents), ctx, maxEvents)
}

// GetHandleID mocks base method.
func (m *MockAdmin) GetHandleID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHandleID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetHandleID indicates an expected call of GetHandleID.
func (mr *MockAdminMockRecorder) GetHandleID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHandleID", reflect.TypeOf((*MockAdmin)(nil).GetHandleID))
}

// GetRoom mocks base method.
func (m *MockAdmin) GetRoom(ctx context.Context, roomID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", ctx, roomID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockAdminMockRecorder) GetRoom(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockAdmin)(nil).GetRoom), ctx, roomID)
}

// GetSessionID mocks base method.
func (m *MockAdmin) GetSessionID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetSessionID indicates an expected call of GetSessionID.
func (mr *MockAdminMockRecorder) GetSessionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionID", reflect.TypeOf((*MockAdmin)(nil).GetSessionID))
}

// KeepAlive mocks base method.
func (m *MockAdmin) KeepAlive(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeepAlive", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// KeepAlive indicates an expected call of KeepAlive.
func (mr *MockAdminMockRecorder) KeepAlive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeepAlive", reflect.TypeOf((*MockAdmin)(nil).KeepAlive), ctx)
}

// ListRTPForwarders mocks base method.
func (m *MockAdmin) ListRTPForwarders(ctx context.Context, roomID int64) ([]janus.RTPForwarderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRTPForwarders", ctx, roomID)
	ret0, _ := ret[0].([]janus.RTPForwarderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRTPForwarders indicates an expected call of ListRTPForwarders.
func (mr *MockAdminMockRecorder) ListRTPForwarders(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRTPForwarders", reflect.TypeOf((*MockAdmin)(nil).ListRTPForwarders), ctx, roomID)
}

// ListRooms mocks base method.
func (m *MockAdmin) ListRooms(ctx context.Context) ([]janus.RoomInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRooms", ctx)
	ret0, _ := ret[0].([]janus.RoomInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRooms indicates an expected call of ListRooms.
func (mr *MockAdminMockRecorder) ListRooms(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRooms", reflect.TypeOf((*MockAdmin)(nil).ListRooms), ctx)
}

// StartKeepalive mocks base method.
func (m *MockAdmin) StartKeepalive() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartKeepalive")
}

// StartKeepalive indicates an expected call of StartKeepalive.
func (mr *MockAdminMockRecorder) StartKeepalive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartKeepalive", reflect.TypeOf((*MockAdmin)(nil).StartKeepalive))
}

// StopKeepalive mocks base method.
func (m *MockAdmin) StopKeepalive() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopKeepalive")
}

// StopKeepalive indicates an expected call of StopKeepalive.
func (mr *MockAdminMockRecorder) StopKeepalive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopKeepalive", reflect.TypeOf((*MockAdmin)(nil).StopKeepalive))
}

// StopRTPForwarder mocks base method.
func (m *MockAdmin) StopRTPForwarder(ctx context.Context, roomID, streamID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopRTPForwarder", ctx, roomID, streamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopRTPForwarder indicates an expected call of StopRTPForwarder.
func (mr *MockAdminMockRecorder) StopRTPForwarder(ctx, roomID, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopRTPForwarder", reflect.TypeOf((*MockAdmin)(nil).StopRTPForwarder), ctx, roomID, streamID)
}
