// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/internal/janus (interfaces: Anchor)
//
// Generated by this command:
//
//	mockgen -destination=mocks/anchor.go -package=mocks github.com/imtaco/audio-rtc-exp/internal/janus Anchor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	janus "github.com/imtaco/audio-rtc-exp/internal/janus"
)

// MockAnchor is a mock of Anchor interface.
type MockAnchor struct {
	ctrl     *gomock.Controller
	recorder *MockAnchorMockRecorder
	isgomock struct{}
}

// MockAnchorMockRecorder is the mock recorder for MockAnchor.
type MockAnchorMockRecorder struct {
	mock *MockAnchor
}

// NewMockAnchor creates a new mock instance.
func NewMockAnchor(ctrl *gomock.Controller) *MockAnchor {
	mock := &MockAnchor{ctrl: ctrl}
	mock.recorder = &MockAnchorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnchor) EXPECT() *MockAnchorMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockAnchor) Check(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockAnchorMockRecorder) Check(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockAnchor)(nil).Check), ctx)
}

// Close mocks base method.
func (m *MockAnchor) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockAnchorMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAnchor)(nil).Close))
}

// Destroy mocks base method.
func (m *MockAnchor) Destroy(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Destroy", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Destroy indicates an expected call of Destroy.
func (mr *MockAnchorMockRecorder) Destroy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroy", reflect.TypeOf((*MockAnchor)(nil).Destroy), ctx)
}

// GetEvents mocks base method.
func (m *MockAnchor) GetEvents(ctx context.Context, maxEvents int) ([]*janus.JanusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvents", ctx, maxEvents)
	ret0, _ := ret[0].([]*janus.JanusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvents indicates an expected call of GetEvents.
func (mr *MockAnchorMockRecorder) GetEvents(ctx, maxEvents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvents", reflect.TypeOf((*MockAnchor)(nil).GetEvents), ctx, maxEvents)
}

// GetHandleID mocks base method.
func (m *MockAnchor) GetHandleID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHandleID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetHandleID indicates an expected call of GetHandleID.
func (mr *MockAnchorMockRecorder) GetHandleID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHandleID", reflect.TypeOf((*MockAnchor)(nil).GetHandleID))
}

// GetSessionID mocks base method.
func (m *MockAnchor) GetSessionID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetSessionID indicates an expected call of GetSessionID.
func (mr *MockAnchorMockRecorder) GetSessionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionID", reflect.TypeOf((*MockAnchor)(nil).GetSessionID))
}

// IceCandidate mocks base method.
func (m *MockAnchor) IceCandidate(ctx context.Context, candidate janus.ICECandidate) (*janus.JanusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IceCandidate", ctx, candidate)
	ret0, _ := ret[0].(*janus.JanusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IceCandidate indicates an expected call of IceCandidate.
func (mr *MockAnchorMockRecorder) IceCandidate(ctx, candidate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IceCandidate", reflect.TypeOf((*MockAnchor)(nil).IceCandidate), ctx, candidate)
}

// Join mocks base method.
func (m *MockAnchor) Join(ctx context.Context, roomID int64, pin, displayName string, jsep *janus.JSEP) (*janus.JanusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Join", ctx, roomID, pin, displayName, jsep)
	ret0, _ := ret[0].(*janus.JanusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Join indicates an expected call of Join.
func (mr *MockAnchorMockRecorder) Join(ctx, roomID, pin, displayName, jsep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockAnchor)(nil).Join), ctx, roomID, pin, displayName, jsep)
}

// KeepAlive mocks base method.
func (m *MockAnchor) KeepAlive(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeepAlive", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// KeepAlive indicates an expected call of KeepAlive.
func (mr *MockAnchorMockRecorder) KeepAlive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeepAlive", reflect.TypeOf((*MockAnchor)(nil).KeepAlive), ctx)
}

// Leave mocks base method.
func (m *MockAnchor) Leave(ctx context.Context) (*janus.JanusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Leave", ctx)
	ret0, _ := ret[0].(*janus.JanusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Leave indicates an expected call of Leave.
func (mr *MockAnchorMockRecorder) Leave(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leave", reflect.TypeOf((*MockAnchor)(nil).Leave), ctx)
}

// StartKeepalive mocks base method.
func (m *MockAnchor) StartKeepalive() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartKeepalive")
}

// StartKeepalive indicates an expected call of StartKeepalive.
func (mr *MockAnchorMockRecorder) StartKeepalive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartKeepalive", reflect.TypeOf((*MockAnchor)(nil).StartKeepalive))
}

// StopKeepalive mocks base method.
func (m *MockAnchor) StopKeepalive() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopKeepalive")
}

// StopKeepalive indicates an expected call of StopKeepalive.
func (mr *MockAnchorMockRecorder) StopKeepalive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopKeepalive", reflect.TypeOf((*MockAnchor)(nil).StopKeepalive))
}
