// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/internal/janus (interfaces: API)
//
// Generated by this command:
//
//	mockgen -destination=mocks/api.go -package=mocks github.com/imtaco/audio-rtc-exp/internal/janus API
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	janus "github.com/imtaco/audio-rtc-exp/internal/janus"
	gomock "go.uber.org/mock/gomock"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
	isgomock struct{}
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// CreateAdminInstance mocks base method.
func (m *MockAPI) CreateAdminInstance(ctx context.Context, adminKey string) (janus.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdminInstance", ctx, adminKey)
	ret0, _ := ret[0].(janus.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdminInstance indicates an expected call of CreateAdminInstance.
func (mr *MockAPIMockRecorder) CreateAdminInstance(ctx, adminKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdminInstance", reflect.TypeOf((*MockAPI)(nil).CreateAdminInstance), ctx, adminKey)
}

// CreateAnchorInstance mocks base method.
func (m *MockAPI) CreateAnchorInstance(ctx context.Context, clientID string, sessionID, handleID int64) (janus.Anchor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAnchorInstance", ctx, clientID, sessionID, handleID)
	ret0, _ := ret[0].(janus.Anchor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAnchorInstance indicates an expected call of CreateAnchorInstance.
func (mr *MockAPIMockRecorder) CreateAnchorInstance(ctx, clientID, sessionID, handleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAnchorInstance", reflect.TypeOf((*MockAPI)(nil).CreateAnchorInstance), ctx, clientID, sessionID, handleID)
}
