// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/internal/jsonrpc (interfaces: Core)
//
// Generated by this command:
//
//	mockgen -destination=pkg/jsonrpc/mocks/core.go -package=mocks github.com/imtaco/audio-rtc-exp/internal/jsonrpc Core
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	jsonrpc "github.com/imtaco/audio-rtc-exp/internal/jsonrpc"
)

// MockCore is a mock of Core interface.
type MockCore[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockCoreMockRecorder[T]
	isgomock struct{}
}

// MockCoreMockRecorder is the mock recorder for MockCore.
type MockCoreMockRecorder[T any] struct {
	mock *MockCore[T]
}

// NewMockCore creates a new mock instance.
func NewMockCore[T any](ctrl *gomock.Controller) *MockCore[T] {
	mock := &MockCore[T]{ctrl: ctrl}
	mock.recorder = &MockCoreMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCore[T]) EXPECT() *MockCoreMockRecorder[T] {
	return m.recorder
}

// Def mocks base method.
func (m *MockCore[T]) Def(method string, handler jsonrpc.MethodHandler[T]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Def", method, handler)
}

// Def indicates an expected call of Def.
func (mr *MockCoreMockRecorder[T]) Def(method, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Def", reflect.TypeOf((*MockCore[T])(nil).Def), method, handler)
}

// DefAsync mocks base method.
func (m *MockCore[T]) DefAsync(method string, handler jsonrpc.AsyncMethodHandler[T]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DefAsync", method, handler)
}

// DefAsync indicates an expected call of DefAsync.
func (mr *MockCoreMockRecorder[T]) DefAsync(method, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefAsync", reflect.TypeOf((*MockCore[T])(nil).DefAsync), method, handler)
}

// NewConn mocks base method.
func (m *MockCore[T]) NewConn(stream jsonrpc.ObjectStream, v *T) jsonrpc.Conn[T] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewConn", stream, v)
	ret0, _ := ret[0].(jsonrpc.Conn[T])
	return ret0
}

// NewConn indicates an expected call of NewConn.
func (mr *MockCoreMockRecorder[T]) NewConn(stream, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConn", reflect.TypeOf((*MockCore[T])(nil).NewConn), stream, v)
}
