// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/common/jsonrpc/redis (interfaces: Peer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/peer.go -package=mocks github.com/imtaco/audio-rtc-exp/common/jsonrpc Peer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	jsonrpc "github.com/imtaco/audio-rtc-exp/internal/jsonrpc"
)

// MockPeer is a mock of Peer interface.
type MockPeer[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockPeerMockRecorder[T]
	isgomock struct{}
}

// MockPeerMockRecorder is the mock recorder for MockPeer.
type MockPeerMockRecorder[T any] struct {
	mock *MockPeer[T]
}

// NewMockPeer creates a new mock instance.
func NewMockPeer[T any](ctrl *gomock.Controller) *MockPeer[T] {
	mock := &MockPeer[T]{ctrl: ctrl}
	mock.recorder = &MockPeerMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeer[T]) EXPECT() *MockPeerMockRecorder[T] {
	return m.recorder
}

// Call mocks base method.
func (m *MockPeer[T]) Call(ctx context.Context, method string, params, result any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", ctx, method, params, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// Call indicates an expected call of Call.
func (mr *MockPeerMockRecorder[T]) Call(ctx, method, params, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockPeer[T])(nil).Call), ctx, method, params, result)
}

// Close mocks base method.
func (m *MockPeer[T]) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPeerMockRecorder[T]) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPeer[T])(nil).Close))
}

// Context mocks base method.
func (m *MockPeer[T]) Context() jsonrpc.MethodContext[T] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(jsonrpc.MethodContext[T])
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockPeerMockRecorder[T]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockPeer[T])(nil).Context))
}

// Def mocks base method.
func (m *MockPeer[T]) Def(method string, handler jsonrpc.MethodHandler[T]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Def", method, handler)
}

// Def indicates an expected call of Def.
func (mr *MockPeerMockRecorder[T]) Def(method, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Def", reflect.TypeOf((*MockPeer[T])(nil).Def), method, handler)
}

// DefAsync mocks base method.
func (m *MockPeer[T]) DefAsync(method string, handler jsonrpc.AsyncMethodHandler[T]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DefAsync", method, handler)
}

// DefAsync indicates an expected call of DefAsync.
func (mr *MockPeerMockRecorder[T]) DefAsync(method, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefAsync", reflect.TypeOf((*MockPeer[T])(nil).DefAsync), method, handler)
}

// Notify mocks base method.
func (m *MockPeer[T]) Notify(ctx context.Context, method string, params any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", ctx, method, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockPeerMockRecorder[T]) Notify(ctx, method, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockPeer[T])(nil).Notify), ctx, method, params)
}

// Open mocks base method.
func (m *MockPeer[T]) Open(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockPeerMockRecorder[T]) Open(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockPeer[T])(nil).Open), ctx)
}
