// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/wsgateway/signal (interfaces: ConnectionGuard)
//
// Generated by this command:
//
//	mockgen -destination=mocks/conn_guard.go -package=singal github.com/imtaco/audio-rtc-exp/wsgateway/signal ConnectionGuard
//

// Package mocks is a generated GoMock package.
package signal

import (
	context "context"
	reflect "reflect"

	jsonrpc "github.com/imtaco/audio-rtc-exp/internal/jsonrpc"
	gomock "go.uber.org/mock/gomock"
)

// MockConnectionGuard is a mock of ConnectionGuard interface.
type MockConnectionGuard struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionGuardMockRecorder
	isgomock struct{}
}

// MockConnectionGuardMockRecorder is the mock recorder for MockConnectionGuard.
type MockConnectionGuardMockRecorder struct {
	mock *MockConnectionGuard
}

// NewMockConnectionGuard creates a new mock instance.
func NewMockConnectionGuard(ctrl *gomock.Controller) *MockConnectionGuard {
	mock := &MockConnectionGuard{ctrl: ctrl}
	mock.recorder = &MockConnectionGuardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionGuard) EXPECT() *MockConnectionGuardMockRecorder {
	return m.recorder
}

// GetServerID mocks base method.
func (m *MockConnectionGuard) GetServerID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetServerID indicates an expected call of GetServerID.
func (mr *MockConnectionGuardMockRecorder) GetServerID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerID", reflect.TypeOf((*MockConnectionGuard)(nil).GetServerID))
}

// MustHold mocks base method.
func (m *MockConnectionGuard) MustHold(mctx jsonrpc.MethodContext[rtcContext]) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MustHold", mctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MustHold indicates an expected call of MustHold.
func (mr *MockConnectionGuardMockRecorder) MustHold(mctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustHold", reflect.TypeOf((*MockConnectionGuard)(nil).MustHold), mctx)
}

// Release mocks base method.
func (m *MockConnectionGuard) Release(mctx jsonrpc.MethodContext[rtcContext]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", mctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockConnectionGuardMockRecorder) Release(mctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockConnectionGuard)(nil).Release), mctx)
}

// Start mocks base method.
func (m *MockConnectionGuard) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockConnectionGuardMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockConnectionGuard)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockConnectionGuard) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockConnectionGuardMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockConnectionGuard)(nil).Stop))
}
