package signal

import (
	"context"

	"github.com/imtaco/audio-rtc-exp/internal/janus"
	"github.com/imtaco/audio-rtc-exp/internal/jsonrpc"
)

type rtcContext struct {
	janus    janus.Anchor
	reqCtx   context.Context // request context
	connID   string          // connID generated by server on connection establishment
	clientID string          // clientID generated by client in the same session
	userID   string
	roomID   string
	joined   bool
	// rlimiter *rate.Limiter
}

type ConnectionGuard interface {
	MustHold(mctx jsonrpc.MethodContext[rtcContext]) (bool, error)
	Release(mctx jsonrpc.MethodContext[rtcContext]) error
	Start(ctx context.Context) error
	Stop()
	GetServerID() string
}
