// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/rooms (interfaces: ResourceManager)
//
// Generated by this command:
//
//	mockgen -destination=mocks/resource_manager.go -package=mocks github.com/imtaco/audio-rtc-exp/rooms ResourceManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockResourceManager is a mock of ResourceManager interface.
type MockResourceManager struct {
	ctrl     *gomock.Controller
	recorder *MockResourceManagerMockRecorder
	isgomock struct{}
}

// MockResourceManagerMockRecorder is the mock recorder for MockResourceManager.
type MockResourceManagerMockRecorder struct {
	mock *MockResourceManager
}

// NewMockResourceManager creates a new mock instance.
func NewMockResourceManager(ctrl *gomock.Controller) *MockResourceManager {
	mock := &MockResourceManager{ctrl: ctrl}
	mock.recorder = &MockResourceManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceManager) EXPECT() *MockResourceManagerMockRecorder {
	return m.recorder
}

// PickJanus mocks base method.
func (m *MockResourceManager) PickJanus() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PickJanus")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PickJanus indicates an expected call of PickJanus.
func (mr *MockResourceManagerMockRecorder) PickJanus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PickJanus", reflect.TypeOf((*MockResourceManager)(nil).PickJanus))
}

// PickMixer mocks base method.
func (m *MockResourceManager) PickMixer() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PickMixer")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PickMixer indicates an expected call of PickMixer.
func (mr *MockResourceManagerMockRecorder) PickMixer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PickMixer", reflect.TypeOf((*MockResourceManager)(nil).PickMixer))
}

// Start mocks base method.
func (m *MockResourceManager) Start(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockResourceManagerMockRecorder) Start(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockResourceManager)(nil).Start), arg0)
}

// Stop mocks base method.
func (m *MockResourceManager) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockResourceManagerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockResourceManager)(nil).Stop))
}
