// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/rooms (interfaces: RoomService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/room_service.go -package=mocks github.com/imtaco/audio-rtc-exp/rooms RoomService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	rooms "github.com/imtaco/audio-rtc-exp/rooms"
	gomock "go.uber.org/mock/gomock"
)

// MockRoomService is a mock of RoomService interface.
type MockRoomService struct {
	ctrl     *gomock.Controller
	recorder *MockRoomServiceMockRecorder
	isgomock struct{}
}

// MockRoomServiceMockRecorder is the mock recorder for MockRoomService.
type MockRoomServiceMockRecorder struct {
	mock *MockRoomService
}

// NewMockRoomService creates a new mock instance.
func NewMockRoomService(ctrl *gomock.Controller) *MockRoomService {
	mock := &MockRoomService{ctrl: ctrl}
	mock.recorder = &MockRoomServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomService) EXPECT() *MockRoomServiceMockRecorder {
	return m.recorder
}

// CreateRoom mocks base method.
func (m *MockRoomService) CreateRoom(ctx context.Context, roomID, pin string, maxAnchors int) (*rooms.RoomResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, roomID, pin, maxAnchors)
	ret0, _ := ret[0].(*rooms.RoomResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockRoomServiceMockRecorder) CreateRoom(ctx, roomID, pin, maxAnchors any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockRoomService)(nil).CreateRoom), ctx, roomID, pin, maxAnchors)
}

// DeleteRoom mocks base method.
func (m *MockRoomService) DeleteRoom(ctx context.Context, roomID string) (*rooms.DeleteRoomResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoom", ctx, roomID)
	ret0, _ := ret[0].(*rooms.DeleteRoomResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRoom indicates an expected call of DeleteRoom.
func (mr *MockRoomServiceMockRecorder) DeleteRoom(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoom", reflect.TypeOf((*MockRoomService)(nil).DeleteRoom), ctx, roomID)
}

// GetRoom mocks base method.
func (m *MockRoomService) GetRoom(ctx context.Context, roomID string) (*rooms.RoomResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", ctx, roomID)
	ret0, _ := ret[0].(*rooms.RoomResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockRoomServiceMockRecorder) GetRoom(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockRoomService)(nil).GetRoom), ctx, roomID)
}

// GetStats mocks base method.
func (m *MockRoomService) GetStats(ctx context.Context) (*rooms.StatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(*rooms.StatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockRoomServiceMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockRoomService)(nil).GetStats), ctx)
}

// ListRooms mocks base method.
func (m *MockRoomService) ListRooms(ctx context.Context) (*rooms.ListRoomsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRooms", ctx)
	ret0, _ := ret[0].(*rooms.ListRoomsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRooms indicates an expected call of ListRooms.
func (mr *MockRoomServiceMockRecorder) ListRooms(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRooms", reflect.TypeOf((*MockRoomService)(nil).ListRooms), ctx)
}

// StartLive mocks base method.
func (m *MockRoomService) StartLive(ctx context.Context, roomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartLive", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartLive indicates an expected call of StartLive.
func (mr *MockRoomServiceMockRecorder) StartLive(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartLive", reflect.TypeOf((*MockRoomService)(nil).StartLive), ctx, roomID)
}
