// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imtaco/audio-rtc-exp/rooms (interfaces: RoomStore)
//
// Generated by this command:
//
//	mockgen -destination=golang/rooms/mocks/room_store.go -package=mocks github.com/imtaco/audio-rtc-exp/rooms RoomStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	constants "github.com/imtaco/audio-rtc-exp/internal/constants"
	etcdstate "github.com/imtaco/audio-rtc-exp/internal/etcdstate"
	rooms "github.com/imtaco/audio-rtc-exp/rooms"
)

// MockRoomStore is a mock of RoomStore interface.
type MockRoomStore struct {
	ctrl     *gomock.Controller
	recorder *MockRoomStoreMockRecorder
	isgomock struct{}
}

// MockRoomStoreMockRecorder is the mock recorder for MockRoomStore.
type MockRoomStoreMockRecorder struct {
	mock *MockRoomStore
}

// NewMockRoomStore creates a new mock instance.
func NewMockRoomStore(ctrl *gomock.Controller) *MockRoomStore {
	mock := &MockRoomStore{ctrl: ctrl}
	mock.recorder = &MockRoomStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomStore) EXPECT() *MockRoomStoreMockRecorder {
	return m.recorder
}

// CreateLiveMeta mocks base method.
func (m *MockRoomStore) CreateLiveMeta(ctx context.Context, roomID, mixerID, janusID, nonce string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLiveMeta", ctx, roomID, mixerID, janusID, nonce)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLiveMeta indicates an expected call of CreateLiveMeta.
func (mr *MockRoomStoreMockRecorder) CreateLiveMeta(ctx, roomID, mixerID, janusID, nonce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLiveMeta", reflect.TypeOf((*MockRoomStore)(nil).CreateLiveMeta), ctx, roomID, mixerID, janusID, nonce)
}

// CreateRoom mocks base method.
func (m *MockRoomStore) CreateRoom(ctx context.Context, roomID string, roomData *etcdstate.Meta) (*etcdstate.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, roomID, roomData)
	ret0, _ := ret[0].(*etcdstate.Meta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockRoomStoreMockRecorder) CreateRoom(ctx, roomID, roomData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockRoomStore)(nil).CreateRoom), ctx, roomID, roomData)
}

// DeleteModuleMark mocks base method.
func (m *MockRoomStore) DeleteModuleMark(ctx context.Context, moduleType, moduleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteModuleMark", ctx, moduleType, moduleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteModuleMark indicates an expected call of DeleteModuleMark.
func (mr *MockRoomStoreMockRecorder) DeleteModuleMark(ctx, moduleType, moduleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModuleMark", reflect.TypeOf((*MockRoomStore)(nil).DeleteModuleMark), ctx, moduleType, moduleID)
}

// DeleteRoom mocks base method.
func (m *MockRoomStore) DeleteRoom(ctx context.Context, roomID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoom", ctx, roomID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRoom indicates an expected call of DeleteRoom.
func (mr *MockRoomStoreMockRecorder) DeleteRoom(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoom", reflect.TypeOf((*MockRoomStore)(nil).DeleteRoom), ctx, roomID)
}

// Exists mocks base method.
func (m *MockRoomStore) Exists(ctx context.Context, roomID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, roomID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockRoomStoreMockRecorder) Exists(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockRoomStore)(nil).Exists), ctx, roomID)
}

// GetAllRooms mocks base method.
func (m *MockRoomStore) GetAllRooms(ctx context.Context) (map[string]*etcdstate.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRooms", ctx)
	ret0, _ := ret[0].(map[string]*etcdstate.Meta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRooms indicates an expected call of GetAllRooms.
func (mr *MockRoomStoreMockRecorder) GetAllRooms(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRooms", reflect.TypeOf((*MockRoomStore)(nil).GetAllRooms), ctx)
}

// GetMixerData mocks base method.
func (m *MockRoomStore) GetMixerData(ctx context.Context, roomID string) (*etcdstate.Mixer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMixerData", ctx, roomID)
	ret0, _ := ret[0].(*etcdstate.Mixer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMixerData indicates an expected call of GetMixerData.
func (mr *MockRoomStoreMockRecorder) GetMixerData(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMixerData", reflect.TypeOf((*MockRoomStore)(nil).GetMixerData), ctx, roomID)
}

// GetRoom mocks base method.
func (m *MockRoomStore) GetRoom(ctx context.Context, roomID string) (*etcdstate.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", ctx, roomID)
	ret0, _ := ret[0].(*etcdstate.Meta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockRoomStoreMockRecorder) GetRoom(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockRoomStore)(nil).GetRoom), ctx, roomID)
}

// GetStats mocks base method.
func (m *MockRoomStore) GetStats(ctx context.Context) (*rooms.RoomStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(*rooms.RoomStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockRoomStoreMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockRoomStore)(nil).GetStats), ctx)
}

// SetModuleMark mocks base method.
func (m *MockRoomStore) SetModuleMark(ctx context.Context, moduleType, moduleID string, label constants.MarkLabel, ttlSeconds int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetModuleMark", ctx, moduleType, moduleID, label, ttlSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetModuleMark indicates an expected call of SetModuleMark.
func (mr *MockRoomStoreMockRecorder) SetModuleMark(ctx, moduleType, moduleID, label, ttlSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetModuleMark", reflect.TypeOf((*MockRoomStore)(nil).SetModuleMark), ctx, moduleType, moduleID, label, ttlSeconds)
}

// StopLiveMeta mocks base method.
func (m *MockRoomStore) StopLiveMeta(ctx context.Context, roomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopLiveMeta", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopLiveMeta indicates an expected call of StopLiveMeta.
func (mr *MockRoomStoreMockRecorder) StopLiveMeta(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopLiveMeta", reflect.TypeOf((*MockRoomStore)(nil).StopLiveMeta), ctx, roomID)
}

// StopRoom mocks base method.
func (m *MockRoomStore) StopRoom(ctx context.Context, roomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopRoom", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopRoom indicates an expected call of StopRoom.
func (mr *MockRoomStoreMockRecorder) StopRoom(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopRoom", reflect.TypeOf((*MockRoomStore)(nil).StopRoom), ctx, roomID)
}
